[package]
name = "write-throughput-sqlite"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "write-throughput-sqlite"
path = "src/main.rs"

[dependencies]
rusqlite = { workspace = true }
clap = { version = "4.0", features = ["derive"] }