[package]
name = "write-throughput"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "write-throughput"
path = "src/main.rs"

[dependencies]
turso = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
tokio = { workspace = true, default-features = true, features = ["full"] }
futures = "0.3"