name: turso_dart
description: "A new Flutter FFI plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.10.0
  plugin_platform_interface: ^2.0.2
  freezed_annotation: ^2.4.4

dev_dependencies:
  ffi: ^2.1.3
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.5.4

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
