[package]
name = "limbo_node"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Limbo Rust API"

[lib]
crate-type = ["cdylib"]

[dependencies]
limbo_core = { workspace = true }
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"

[build-dependencies]
napi-build = "2.0.1"
