# This is a workflow file that will be used to run the labeler action on pull requests
# The action will add labels to the pull request based on the files that were changed

name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          sync-labels: true
